# Generated by Django 4.1.3 on 2022-11-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('holiday', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True)),
                ('msg', models.TextField(max_length=5000)),
                ('scheduled_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500)),
                ('quote', models.CharField(max_length=500)),
            ],
        ),
    ]
