# Generated by Django 4.1.3 on 2022-11-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scheduled_at',
            field=models.DateField(),
        ),
    ]
